version: '3.8'
services:
  mongodb:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  users:
    build:
      context: ./user-service
    container_name: users_service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/users_db
    depends_on:
      - mongodb

  products:
    build:
      context: ./product-service
    container_name: products_service
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/products_db
    depends_on:
      - mongodb

  orders:
    build:
      context: ./order-service
    container_name: orders_service
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/orders_db
    depends_on:
      - mongodb

volumes:
  mongodb_data: